import { v7 } from 'uuid';

/**
 * Creates row IDs. IDs are generated by the app, not the database, and are
 * time-ordered UUIDv7 (ADR-007), so they sort by creation time.
 */
export interface IdGenerator {
  next(): string;
}

export const uuidV7Ids: IdGenerator = {
  next: () => v7(),
};

/** A UUID, as an ID the app made: any version, either case. */
export const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
