// Prepares the local stack's logins, once: `node deploy/compose/prepare.ts`.
// The stack ships no passwords (SEC-OPS-08). This writes deploy/compose/.env,
// which git ignores, with a fresh random password for every login the services
// need, and Zitadel's master key. compose.yaml refuses to start without them
// (`${NAME:?}`), so a stack can't come up on a default. An existing .env is
// kept as it is: the database keeps the passwords it was created with.
import { randomBytes } from 'node:crypto';
import { existsSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

/** Where compose reads the file from: its own folder. */
export const ENV_FILE = fileURLToPath(new URL('./.env', import.meta.url));

/** Every login the stack needs, one random password each. */
export const PASSWORDS = [
  'AGENTX_LOCAL_POSTGRES_ADMIN_PASSWORD',
  'AGENTX_LOCAL_DB_OWNER_PASSWORD',
  'AGENTX_LOCAL_DB_APP_PASSWORD',
  'AGENTX_LOCAL_DB_BACKUP_PASSWORD',
  'AGENTX_LOCAL_ZITADEL_DB_PASSWORD',
  'AGENTX_LOCAL_ZITADEL_ADMIN_PASSWORD',
] as const;

/** Zitadel encrypts its own secrets with this; it must be exactly 32 characters. */
export const MASTER_KEY = 'AGENTX_LOCAL_ZITADEL_MASTERKEY';

export type Random = (bytes: number) => Buffer;

/**
 * 128 random bits as hex, plus one character of each kind Zitadel's default
 * password rules ask for (upper case, lower case, digit, symbol), so the same
 * shape serves every login. Nothing in it means anything to a shell, YAML or
 * a compose .env file.
 */
export function newPassword(random: Random = randomBytes): string {
  return `${random(16).toString('hex')}aZ9!`;
}

/** 32 characters, as Zitadel requires. */
export function newMasterKey(random: Random = randomBytes): string {
  return random(16).toString('hex');
}

/** The file's text: one `NAME=value` line per login, in a fixed order. */
export function renderEnv(values: Readonly<Record<string, string>>): string {
  const lines = Object.entries(values).map(([name, value]) => `${name}=${value}`);
  return `# Generated by deploy/compose/prepare.ts. Local logins: never commit, never share.\n${lines.join('\n')}\n`;
}

export function generate(random: Random = randomBytes): Record<string, string> {
  return {
    ...Object.fromEntries(PASSWORDS.map((name) => [name, newPassword(random)])),
    [MASTER_KEY]: newMasterKey(random),
  };
}

/** Writes the file unless it exists. Returns what happened, never a value. */
export function prepare(file: string = ENV_FILE, random: Random = randomBytes): 'created' | 'kept' {
  if (existsSync(file)) return 'kept';
  writeFileSync(file, renderEnv(generate(random)), { mode: 0o600, flag: 'wx' });
  return 'created';
}

if (import.meta.main) {
  const outcome = prepare();
  console.log(
    outcome === 'created'
      ? `Wrote ${ENV_FILE} with new logins for the local stack.`
      : `Kept ${ENV_FILE}: the stack's logins already exist. Delete it (and the stack's volumes) to start afresh.`,
  );
}
