import { createPrivateKey, createPublicKey, sign, verify } from 'node:crypto';
import { mkdirSync, mkdtempSync, readFileSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';

import { afterAll, describe, expect, it } from 'vitest';

import {
  ENV_FILE,
  generate,
  HalfKeyPair,
  IncompleteEnvFile,
  LOGIN_CLIENT_KEYS,
  MASTER_KEY,
  NotAKeyFile,
  newKeyPair,
  newMasterKey,
  newPassword,
  PASSWORDS,
  prepare,
  prepareEnv,
  prepareKeys,
  renderEnv,
  SECRETS_DIR,
  VARIABLES,
} from './prepare.ts';

/** A predictable byte source, so a test can check the shape without the randomness. */
const bytes = (fill: number) => (count: number) => Buffer.alloc(count, fill);

/** A stand-in key pair of plain words, so a test can check where each half goes without making keys. */
const wordsPair = () => ({ publicPem: 'public half', privatePem: 'private half' });

/**
 * The first line of a PEM block, assembled rather than written out: both secret
 * scanners read the words of one as a key wherever they appear (tooling/git-hooks
 * rule `private-key`), and the pre-commit hook refuses the line.
 */
const pemHeader = (kind: string): string => `${'-'.repeat(5)}BEGIN ${kind} KEY${'-'.repeat(5)}`;

const dir = mkdtempSync(path.join(tmpdir(), 'agentx-prepare-'));

/** A folder of its own per test, so one test's files are never another's. */
const keysDir = (name: string): string => {
  const made = path.join(dir, `keys-${name}`);
  mkdirSync(made, { recursive: true });
  return made;
};

afterAll(() => {
  rmSync(dir, { recursive: true, force: true });
});

describe('SEC-OPS-08 the local stack has no default logins: prepare generates them', () => {
  it('writes both where compose reads them: next to compose.yaml', () => {
    const root = path.resolve(import.meta.dirname, '../..');
    const inRepo = (file: string): string => path.relative(root, file).replaceAll('\\', '/');
    expect(inRepo(ENV_FILE)).toBe('deploy/compose/.env');
    expect(inRepo(SECRETS_DIR)).toBe('deploy/compose/secrets');
  });

  it('makes a password from 128 random bits, with every kind of character Zitadel asks for', () => {
    const password = newPassword();
    expect(password).toMatch(/^[0-9a-f]{32}aZ9!$/);
    expect([/[A-Z]/, /[a-z]/, /[0-9]/, /[^A-Za-z0-9]/].every((kind) => kind.test(password))).toBe(true);
    expect(newPassword()).not.toBe(password);
  });

  it('makes a master key of exactly 32 characters, as Zitadel requires', () => {
    expect(newMasterKey()).toMatch(/^[0-9a-f]{32}$/);
    expect(newMasterKey()).not.toBe(newMasterKey());
  });

  it("makes the login container's key pair: RSA, 3072 bits, the two halves of one key", () => {
    const pair = newKeyPair();
    const publicKey = createPublicKey(pair.publicPem);
    const privateKey = createPrivateKey(pair.privatePem);
    expect(publicKey.asymmetricKeyType).toBe('rsa');
    expect(publicKey.asymmetricKeyDetails?.modulusLength).toBe(3072);
    const message = Buffer.from('a call to Zitadel');
    expect(verify('sha256', message, publicKey, sign('sha256', message, privateKey))).toBe(true);
    expect(newKeyPair().publicPem).not.toBe(pair.publicPem);
  });

  it('draws every value afresh, so nothing is shared between logins', () => {
    let draw = 0;
    const values = generate((count) => Buffer.alloc(count, draw++));
    expect(Object.keys(values)).toEqual(VARIABLES);
    expect(new Set(Object.values(values)).size).toBe(VARIABLES.length);
  });

  it('writes one line per variable, in a fixed order, with a warning on top and no key in the file', () => {
    const text = renderEnv(generate(bytes(0xab)));
    expect(text.split('\n')).toEqual([
      '# Generated by deploy/compose/prepare.ts. Local logins: never commit, never share.',
      ...PASSWORDS.map((name) => `${name}=${'ab'.repeat(16)}aZ9!`),
      `${MASTER_KEY}=${'ab'.repeat(16)}`,
      '',
    ]);
    expect(text).not.toContain('LOGIN_CLIENT');
  });

  it('creates the file once, read-write for its owner only, and keeps it on later runs', () => {
    const file = path.join(dir, '.env');
    expect(prepareEnv(file, bytes(0x01))).toBe('created');
    const written = readFileSync(file, 'utf8');
    expect(written).toContain(`AGENTX_LOCAL_DB_APP_PASSWORD=${'01'.repeat(16)}aZ9!`);
    // Windows keeps no such bits; elsewhere the file is private to its owner.
    if (process.platform !== 'win32') expect(statSync(file).mode & 0o777).toBe(0o600);

    expect(prepareEnv(file, bytes(0x02))).toBe('kept');
    expect(readFileSync(file, 'utf8')).toBe(written);
  });

  it.each([
    ["Zitadel's master key, which what it has encrypted depends on", [MASTER_KEY]],
    ["the database superuser's login, which the database files depend on", ['AGENTX_LOCAL_POSTGRES_ADMIN_PASSWORD']],
  ])('refuses a file lacking %s, naming it, and changes nothing', (_, lacking) => {
    const file = path.join(dir, `lacking-${lacking.join('-')}.env`);
    const older = renderEnv(
      Object.fromEntries(Object.entries(generate(bytes(0x06))).filter(([name]) => !lacking.includes(name))),
    );
    writeFileSync(file, older);
    expect(() => prepareEnv(file, bytes(0x07))).toThrow(IncompleteEnvFile);
    try {
      prepareEnv(file, bytes(0x07));
    } catch (error) {
      expect((error as IncompleteEnvFile).missing).toEqual(lacking);
    }
    expect(readFileSync(file, 'utf8')).toBe(older);
  });
});

describe('the login key pair is two files, the shape Zitadel and the login container read (ADR-003)', () => {
  it('writes each half to the file name Azure mounts it under, and keeps them on later runs', () => {
    const made = keysDir('written');
    expect(prepareKeys(made, wordsPair)).toBe('created');
    const file = (half: 'public' | 'private'): string => path.join(made, LOGIN_CLIENT_KEYS[half]);
    expect(readFileSync(file('public'), 'utf8')).toBe('public half');
    expect(readFileSync(file('private'), 'utf8')).toBe('private half');

    expect(prepareKeys(made, () => ({ publicPem: 'another', privatePem: 'another' }))).toBe('kept');
    expect(readFileSync(file('public'), 'utf8')).toBe('public half');
  });

  it('writes PEM text, not base64: each file is the key the program parses', () => {
    const made = keysDir('pem');
    prepareKeys(made, newKeyPair);
    const publicPem = readFileSync(path.join(made, LOGIN_CLIENT_KEYS.public), 'utf8');
    const privatePem = readFileSync(path.join(made, LOGIN_CLIENT_KEYS.private), 'utf8');
    expect(publicPem.startsWith(pemHeader('PUBLIC'))).toBe(true);
    expect(privatePem.startsWith(pemHeader('PRIVATE'))).toBe(true);
    const message = Buffer.from('a call to Zitadel');
    const signature = sign('sha256', message, createPrivateKey(privatePem));
    expect(verify('sha256', message, createPublicKey(publicPem), signature)).toBe(true);
  });

  it('every container can read them: they run as their own users with no capability to override a mode', () => {
    const made = keysDir('mode');
    prepareKeys(made, wordsPair);
    if (process.platform === 'win32') return;
    for (const half of ['public', 'private'] as const) {
      expect(statSync(path.join(made, LOGIN_CLIENT_KEYS[half])).mode & 0o777).toBe(0o644);
    }
  });

  it.each(['public', 'private'] as const)('refuses a %s half left without the other, and changes nothing', (half) => {
    const made = keysDir(`half-${half}`);
    const there = path.join(made, LOGIN_CLIENT_KEYS[half]);
    writeFileSync(there, 'an older half');
    expect(() => prepareKeys(made, wordsPair)).toThrow(HalfKeyPair);
    try {
      prepareKeys(made, wordsPair);
    } catch (error) {
      expect((error as HalfKeyPair).present).toBe(LOGIN_CLIENT_KEYS[half]);
    }
    expect(readFileSync(there, 'utf8')).toBe('an older half');
  });

  it.each(['public', 'private'] as const)(
    'refuses a folder left where the %s half belongs, which is what starting the stack first makes',
    (half) => {
      const made = keysDir(`folder-${half}`);
      mkdirSync(path.join(made, LOGIN_CLIENT_KEYS[half]));
      expect(() => prepareKeys(made, wordsPair)).toThrow(NotAKeyFile);
      try {
        prepareKeys(made, wordsPair);
      } catch (error) {
        expect((error as NotAKeyFile).path).toBe(path.join(made, LOGIN_CLIENT_KEYS[half]));
      }
    },
  );

  it('makes the folder when it is not there, so one run prepares a fresh clone', () => {
    const made = path.join(dir, 'never-made', 'secrets');
    expect(prepareKeys(made, wordsPair)).toBe('created');
    expect(readFileSync(path.join(made, LOGIN_CLIENT_KEYS.public), 'utf8')).toBe('public half');
  });

  it('one run does both, and says which of the two was already there', () => {
    const file = path.join(dir, 'both.env');
    const made = keysDir('both');
    expect(prepare(file, made, bytes(0x08), wordsPair)).toEqual({ env: 'created', keys: 'created' });
    expect(prepare(file, made, bytes(0x09), wordsPair)).toEqual({ env: 'kept', keys: 'kept' });
  });
});
