import { createPrivateKey, createPublicKey, sign, verify } from 'node:crypto';
import { mkdtempSync, readFileSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';

import { afterAll, describe, expect, it } from 'vitest';

import {
  ENV_FILE,
  generate,
  IncompleteEnvFile,
  LOGIN_CLIENT_KEYS,
  MASTER_KEY,
  newKeyPair,
  newMasterKey,
  newPassword,
  PASSWORDS,
  prepare,
  renderEnv,
  VARIABLES,
} from './prepare.ts';

/** A predictable byte source, so a test can check the shape without the randomness. */
const bytes = (fill: number) => (count: number) => Buffer.alloc(count, fill);

/** A stand-in key pair of plain words, so a test can check where each half goes without making keys. */
const wordsPair = () => ({ publicPem: 'public half', privatePem: 'private half' });
const base64 = (text: string): string => Buffer.from(text).toString('base64');

const dir = mkdtempSync(path.join(tmpdir(), 'agentx-prepare-'));
afterAll(() => {
  rmSync(dir, { recursive: true, force: true });
});

describe('SEC-OPS-08 the local stack has no default logins: prepare generates them', () => {
  it('writes the file where compose reads it: next to compose.yaml', () => {
    const root = path.resolve(import.meta.dirname, '../..');
    expect(path.relative(root, ENV_FILE).replaceAll('\\', '/')).toBe('deploy/compose/.env');
  });

  it('makes a password from 128 random bits, with every kind of character Zitadel asks for', () => {
    const password = newPassword();
    expect(password).toMatch(/^[0-9a-f]{32}aZ9!$/);
    expect([/[A-Z]/, /[a-z]/, /[0-9]/, /[^A-Za-z0-9]/].every((kind) => kind.test(password))).toBe(true);
    expect(newPassword()).not.toBe(password);
  });

  it('makes a master key of exactly 32 characters, as Zitadel requires', () => {
    expect(newMasterKey()).toMatch(/^[0-9a-f]{32}$/);
    expect(newMasterKey()).not.toBe(newMasterKey());
  });

  it("makes the login container's key pair: RSA, 3072 bits, the two halves of one key", () => {
    const pair = newKeyPair();
    const publicKey = createPublicKey(pair.publicPem);
    const privateKey = createPrivateKey(pair.privatePem);
    expect(publicKey.asymmetricKeyType).toBe('rsa');
    expect(publicKey.asymmetricKeyDetails?.modulusLength).toBe(3072);
    const message = Buffer.from('a call to Zitadel');
    expect(verify('sha256', message, publicKey, sign('sha256', message, privateKey))).toBe(true);
    expect(newKeyPair().publicPem).not.toBe(pair.publicPem);
  });

  it('draws every value afresh, so nothing is shared between logins', () => {
    let draw = 0;
    const values = generate((count) => Buffer.alloc(count, draw++));
    expect(Object.keys(values)).toEqual(VARIABLES);
    expect(new Set(Object.values(values)).size).toBe(VARIABLES.length);
  });

  it('writes one line per variable, in a fixed order, the key halves as base64 of their text, with a warning on top', () => {
    const text = renderEnv(generate(bytes(0xab), wordsPair));
    expect(text.split('\n')).toEqual([
      '# Generated by deploy/compose/prepare.ts. Local logins: never commit, never share.',
      ...PASSWORDS.map((name) => `${name}=${'ab'.repeat(16)}aZ9!`),
      `${MASTER_KEY}=${'ab'.repeat(16)}`,
      `${LOGIN_CLIENT_KEYS.public}=${base64('public half')}`,
      `${LOGIN_CLIENT_KEYS.private}=${base64('private half')}`,
      '',
    ]);
  });

  it('creates the file once, read-write for its owner only, and keeps it on later runs', () => {
    const file = path.join(dir, '.env');
    expect(prepare(file, bytes(0x01), wordsPair)).toBe('created');
    const written = readFileSync(file, 'utf8');
    expect(written).toContain(`AGENTX_LOCAL_DB_APP_PASSWORD=${'01'.repeat(16)}aZ9!`);
    // Windows keeps no such bits; elsewhere the file is private to its owner.
    if (process.platform !== 'win32') expect(statSync(file).mode & 0o777).toBe(0o600);

    expect(prepare(file, bytes(0x02), wordsPair)).toBe('kept');
    expect(readFileSync(file, 'utf8')).toBe(written);
  });

  it('adds only what an older file lacks, and changes nothing it has', () => {
    const file = path.join(dir, 'older.env');
    const older = renderEnv(
      Object.fromEntries(
        Object.entries(generate(bytes(0x03), wordsPair)).filter(([name]) => !name.startsWith('AGENTX_LOCAL_LOGIN')),
      ),
    ).trimEnd();
    writeFileSync(file, older);
    expect(prepare(file, bytes(0x04), wordsPair)).toBe('added');
    expect(readFileSync(file, 'utf8')).toBe(
      `${older}\n${LOGIN_CLIENT_KEYS.public}=${base64('public half')}\n${LOGIN_CLIENT_KEYS.private}=${base64('private half')}\n`,
    );
    expect(prepare(file, bytes(0x05), wordsPair)).toBe('kept');
  });

  it.each([
    ['one half of the login key pair', [LOGIN_CLIENT_KEYS.private]],
    ["Zitadel's master key, which what it has encrypted depends on", [MASTER_KEY]],
    ["the database superuser's login, which the database files depend on", ['AGENTX_LOCAL_POSTGRES_ADMIN_PASSWORD']],
  ])('refuses a file lacking %s, naming it, and changes nothing', (_, lacking) => {
    const file = path.join(dir, `lacking-${lacking.join('-')}.env`);
    const older = renderEnv(
      Object.fromEntries(Object.entries(generate(bytes(0x06), wordsPair)).filter(([name]) => !lacking.includes(name))),
    );
    writeFileSync(file, older);
    expect(() => prepare(file, bytes(0x07), wordsPair)).toThrow(IncompleteEnvFile);
    try {
      prepare(file, bytes(0x07), wordsPair);
    } catch (error) {
      expect((error as IncompleteEnvFile).missing).toEqual(lacking);
    }
    expect(readFileSync(file, 'utf8')).toBe(older);
  });
});
