import { mkdtempSync, readFileSync, rmSync, statSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';

import { afterAll, describe, expect, it } from 'vitest';

import { generate, MASTER_KEY, newMasterKey, newPassword, PASSWORDS, prepare, renderEnv } from './prepare.ts';

/** A predictable byte source, so a test can check the shape without the randomness. */
const bytes = (fill: number) => (count: number) => Buffer.alloc(count, fill);

const dir = mkdtempSync(path.join(tmpdir(), 'agentx-prepare-'));
afterAll(() => {
  rmSync(dir, { recursive: true, force: true });
});

describe('SEC-OPS-08 the local stack has no default logins: prepare generates them', () => {
  it('makes a password from 128 random bits, with every kind of character Zitadel asks for', () => {
    const password = newPassword();
    expect(password).toMatch(/^[0-9a-f]{32}aZ9!$/);
    expect([/[A-Z]/, /[a-z]/, /[0-9]/, /[^A-Za-z0-9]/].every((kind) => kind.test(password))).toBe(true);
    expect(newPassword()).not.toBe(password);
  });

  it('makes a master key of exactly 32 characters, as Zitadel requires', () => {
    expect(newMasterKey()).toMatch(/^[0-9a-f]{32}$/);
    expect(newMasterKey()).not.toBe(newMasterKey());
  });

  it('draws every value from the byte source, so nothing is shared between logins', () => {
    let draw = 0;
    const values = generate((count) => Buffer.alloc(count, draw++));
    expect(new Set(Object.values(values)).size).toBe(PASSWORDS.length + 1);
  });

  it('writes one line per login, in a fixed order, with a warning on top', () => {
    const text = renderEnv(generate(bytes(0xab)));
    expect(text.split('\n')).toEqual([
      '# Generated by deploy/compose/prepare.ts. Local logins: never commit, never share.',
      ...PASSWORDS.map((name) => `${name}=${'ab'.repeat(16)}aZ9!`),
      `${MASTER_KEY}=${'ab'.repeat(16)}`,
      '',
    ]);
  });

  it('creates the file once, read-write for its owner only, and keeps it on later runs', () => {
    const file = path.join(dir, '.env');
    expect(prepare(file, bytes(0x01))).toBe('created');
    const written = readFileSync(file, 'utf8');
    expect(written).toContain(`AGENTX_LOCAL_DB_APP_PASSWORD=${'01'.repeat(16)}aZ9!`);
    // Windows keeps no such bits; elsewhere the file is private to its owner.
    if (process.platform !== 'win32') expect(statSync(file).mode & 0o777).toBe(0o600);

    expect(prepare(file, bytes(0x02))).toBe('kept');
    expect(readFileSync(file, 'utf8')).toBe(written);
  });
});
