// Prepares the local stack's logins, once: `node deploy/compose/prepare.ts`.
// The stack ships no passwords (SEC-OPS-08). This writes three things, all of
// which git ignores:
//
// - deploy/compose/.env, with a fresh random password for every login the
//   services need and Zitadel's master key. compose.yaml refuses to start
//   without them (`${NAME:?}`), so a stack can't come up on a default. An
//   existing .env keeps every value it has, since the database keeps the
//   passwords it was created with, and a gap in it means the stack is started
//   afresh
// - deploy/compose/secrets, with the key pair the login container signs its
//   calls to Zitadel with, a PEM file each. They are files rather than .env
//   values because that is how each program reads a key: Zitadel takes the
//   public half by `Path` and the login container the private half by
//   `SYSTEM_USER_PRIVATE_KEY_FILE`, both of which name a file holding PEM
//   text. Azure mounts the same two names from Key Vault at the same path
//   (deploy/azure, G2d-2), so the settings are the same string in both
// - deploy/compose/secrets/app-keys, with the app's own keys (ADR-011 §2), one
//   file per key as the API reads them (`key-<purpose>-v1`, 32 random bytes as
//   base64url). A key once written is kept: the stack's data depends on it
import { generateKeyPairSync, randomBytes } from 'node:crypto';
import { mkdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { PURPOSES } from '../../packages/platform/src/keys/purposes.ts';

/** Where compose reads the file from: its own folder. */
export const ENV_FILE = fileURLToPath(new URL('./.env', import.meta.url));

/** Where compose mounts the key pair from: a folder of its own, so nothing else is mounted with it. */
export const SECRETS_DIR = fileURLToPath(new URL('./secrets', import.meta.url));

/** Every login the stack needs, one random password each. */
export const PASSWORDS = [
  'AGENTX_LOCAL_POSTGRES_ADMIN_PASSWORD',
  'AGENTX_LOCAL_DB_OWNER_PASSWORD',
  'AGENTX_LOCAL_DB_APP_PASSWORD',
  'AGENTX_LOCAL_DB_BACKUP_PASSWORD',
  'AGENTX_LOCAL_ZITADEL_DB_PASSWORD',
  'AGENTX_LOCAL_ZITADEL_ADMIN_PASSWORD',
] as const;

/** Zitadel encrypts its own secrets with this; it must be exactly 32 characters. */
export const MASTER_KEY = 'AGENTX_LOCAL_ZITADEL_MASTERKEY';

/**
 * The login container's key pair (ADR-003), a PEM file each: Zitadel is given
 * the public half and the login container the private half, and neither ever
 * holds the other's. Named for the Key Vault secrets that hold the same two on
 * Azure (`GRANTS` in deploy/azure/policy.ts), so both deployments mount the
 * same file names.
 */
export const LOGIN_CLIENT_KEYS = {
  public: 'login-client-public-key',
  private: 'login-client-private-key',
} as const;

/**
 * The app's keys, in a folder of their own that compose mounts into the API
 * alone, at the path Azure mounts them (AGENTX_KEYS_DIR is /mnt/secrets in both).
 */
export const APP_KEYS = 'app-keys';

/** Every variable the .env file holds, in the order it's written. */
export const VARIABLES: readonly string[] = [...PASSWORDS, MASTER_KEY];

export type Random = (bytes: number) => Buffer;
export type KeyPair = () => { readonly publicPem: string; readonly privatePem: string };

/**
 * 128 random bits as hex, plus one character of each kind Zitadel's default
 * password rules ask for (upper case, lower case, digit, symbol), so the same
 * shape serves every login. Nothing in it means anything to a shell, YAML or
 * a compose .env file.
 */
export function newPassword(random: Random = randomBytes): string {
  return `${random(16).toString('hex')}aZ9!`;
}

/** 32 characters, as Zitadel requires. */
export function newMasterKey(random: Random = randomBytes): string {
  return random(16).toString('hex');
}

/** RSA, as Zitadel's system users take it: 3072 bits, the public half as SPKI and the private as PKCS#8. */
export const newKeyPair: KeyPair = () => {
  const pair = generateKeyPairSync('rsa', {
    modulusLength: 3072,
    publicKeyEncoding: { type: 'spki', format: 'pem' },
    privateKeyEncoding: { type: 'pkcs8', format: 'pem' },
  });
  return { publicPem: pair.publicKey, privatePem: pair.privateKey };
};

/** The file's text: one `NAME=value` line per variable, in a fixed order. */
export function renderEnv(values: Readonly<Record<string, string>>): string {
  const lines = Object.entries(values).map(([name, value]) => `${name}=${value}`);
  return `# Generated by deploy/compose/prepare.ts. Local logins: never commit, never share.\n${lines.join('\n')}\n`;
}

export function generate(random: Random = randomBytes): Record<string, string> {
  return {
    ...Object.fromEntries(PASSWORDS.map((name) => [name, newPassword(random)])),
    [MASTER_KEY]: newMasterKey(random),
  };
}

/** The names an existing file already sets. */
const namesIn = (text: string): Set<string> =>
  new Set(
    text
      .split('\n')
      .filter((line) => !line.startsWith('#') && line.includes('='))
      .map((line) => line.slice(0, line.indexOf('=')).trim()),
  );

/** The file lacks values the stack's data depends on. Names only, never values. */
export class IncompleteEnvFile extends Error {
  readonly missing: readonly string[];

  constructor(file: string, missing: readonly string[]) {
    super(
      `${file} lacks ${missing.join(', ')}, which the stack's data depends on: ` +
        'stop the stack with its volumes (docker compose -f deploy/compose/compose.yaml down --volumes), delete the file, and run prepare again',
    );
    this.name = 'IncompleteEnvFile';
    this.missing = missing;
  }
}

/**
 * Something that isn't a file sits where a key belongs. Docker makes a folder
 * in place of a bind-mounted file that isn't there, so this is what a stack
 * started before prepare leaves behind: the container would then be given a
 * folder to read a key from.
 */
export class NotAKeyFile extends Error {
  readonly path: string;

  constructor(file: string) {
    super(
      `${file} is not a file, which is what Docker leaves when the stack is started before prepare: ` +
        'stop the stack (docker compose -f deploy/compose/compose.yaml down), delete deploy/compose/secrets, and run prepare again',
    );
    this.name = 'NotAKeyFile';
    this.path = file;
  }
}

/** One half of the login key pair is there without the other, which would sign nothing Zitadel accepts. */
export class HalfKeyPair extends Error {
  readonly present: string;

  constructor(dir: string, present: string) {
    super(
      `${dir} holds ${present} without its other half, so the login container would sign calls Zitadel refuses: ` +
        'delete both files and run prepare again (the stack keeps its data; the pair is read afresh at every start)',
    );
    this.name = 'HalfKeyPair';
    this.present = present;
  }
}

/**
 * The key pair as two PEM files, written only when neither is there: Zitadel
 * and the login container read them afresh at every start, so a new pair works
 * on a stack that already has data, but a new half beside an old one would not.
 *
 * Readable by anyone on this machine, because the containers read them as their
 * own unprivileged users with every capability dropped, and a file only its
 * owner can read would be a file they can't. What that costs is a throwaway
 * pair, made per machine, never committed and never used anywhere but this
 * stack; on Azure the same two files are mounted from Key Vault by the platform
 * (deploy/azure/apps.bicep).
 */
export function prepareKeys(dir: string = SECRETS_DIR, keyPair: KeyPair = newKeyPair): 'created' | 'kept' {
  const files = {
    public: path.join(dir, LOGIN_CLIENT_KEYS.public),
    private: path.join(dir, LOGIN_CLIENT_KEYS.private),
  };
  mkdirSync(dir, { recursive: true });
  /** Whether that half is there, refusing anything in its place that isn't a file. */
  const keyAt = (file: string): boolean => {
    const found = statSync(file, { throwIfNoEntry: false });
    if (found === undefined) return false;
    if (!found.isFile()) throw new NotAKeyFile(file);
    return true;
  };
  const there = (['public', 'private'] as const).filter((half) => keyAt(files[half]));
  if (there.length === 2) return 'kept';
  const half = there[0];
  if (half !== undefined) throw new HalfKeyPair(dir, LOGIN_CLIENT_KEYS[half]);
  const keys = keyPair();
  writeFileSync(files.public, keys.publicPem, { mode: 0o644 });
  writeFileSync(files.private, keys.privatePem, { mode: 0o644 });
  return 'created';
}

/**
 * One version 1 key for each of the app's purposes, written only where there
 * is none: the stack's data is sealed with the keys it has, so a key is never
 * replaced. Readable by anyone on this machine for the same reason as the key
 * pair: the API runs as its own unprivileged user.
 */
export function prepareAppKeys(
  dir: string = path.join(SECRETS_DIR, APP_KEYS),
  random: Random = randomBytes,
): 'created' | 'kept' {
  mkdirSync(dir, { recursive: true });
  let created = false;
  for (const purpose of PURPOSES) {
    const file = path.join(dir, `key-${purpose}-v1`);
    const found = statSync(file, { throwIfNoEntry: false });
    if (found !== undefined && !found.isFile()) throw new NotAKeyFile(file);
    if (found !== undefined) continue;
    writeFileSync(file, `${random(32).toString('base64url')}\n`, { mode: 0o644, flag: 'wx' });
    created = true;
  }
  return created ? 'created' : 'kept';
}

/**
 * Writes the .env file unless it exists: `wx` lets the file system decide, so
 * two runs at once can't both write it. An existing file keeps every value it
 * has, and any gap throws IncompleteEnvFile. Returns what happened, never a value.
 */
export function prepareEnv(file: string = ENV_FILE, random: Random = randomBytes): 'created' | 'kept' {
  try {
    writeFileSync(file, renderEnv(generate(random)), { mode: 0o600, flag: 'wx' });
    return 'created';
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== 'EEXIST') throw error;
  }
  const present = namesIn(readFileSync(file, 'utf8'));
  const missing = VARIABLES.filter((name) => !present.has(name));
  if (missing.length > 0) throw new IncompleteEnvFile(file, missing);
  return 'kept';
}

/** What one run did to each of the three, so the operator is told which was already there. */
export interface Prepared {
  readonly env: 'created' | 'kept';
  readonly keys: 'created' | 'kept';
  readonly appKeys: 'created' | 'kept';
}

/** The whole preparation: the logins, the login key pair, then the app's keys. */
export function prepare(
  file: string = ENV_FILE,
  dir: string = SECRETS_DIR,
  random: Random = randomBytes,
  keyPair: KeyPair = newKeyPair,
): Prepared {
  return {
    env: prepareEnv(file, random),
    keys: prepareKeys(dir, keyPair),
    appKeys: prepareAppKeys(path.join(dir, APP_KEYS), random),
  };
}

if (import.meta.main) {
  try {
    const done = prepare();
    console.log(
      done.env === 'created'
        ? `Wrote ${ENV_FILE} with new logins for the local stack.`
        : `Kept ${ENV_FILE}: the stack's logins already exist. Delete it (and the stack's volumes) to start afresh.`,
    );
    console.log(
      done.keys === 'created'
        ? `Wrote the login container's key pair to ${SECRETS_DIR}.`
        : `Kept the login container's key pair in ${SECRETS_DIR}.`,
    );
    console.log(
      done.appKeys === 'created'
        ? `Wrote the app's missing keys to ${path.join(SECRETS_DIR, APP_KEYS)}.`
        : `Kept the app's keys in ${path.join(SECRETS_DIR, APP_KEYS)}.`,
    );
  } catch (error) {
    const told = error instanceof IncompleteEnvFile || error instanceof HalfKeyPair || error instanceof NotAKeyFile;
    if (!told) throw error;
    console.error(error.message);
    process.exitCode = 1;
  }
}
