// Prepares the local stack's logins, once: `node deploy/compose/prepare.ts`.
// The stack ships no passwords (SEC-OPS-08). This writes deploy/compose/.env,
// which git ignores, with a fresh random password for every login the services
// need, Zitadel's master key, and the key pair the login container signs its
// calls to Zitadel with. compose.yaml refuses to start without them
// (`${NAME:?}`), so a stack can't come up on a default. An existing .env keeps
// every value it has, since the database keeps the passwords it was created
// with; a value the stack has come to need since is added to it.
import { generateKeyPairSync, randomBytes } from 'node:crypto';
import { appendFileSync, readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

/** Where compose reads the file from: its own folder. */
export const ENV_FILE = fileURLToPath(new URL('./.env', import.meta.url));

/** Every login the stack needs, one random password each. */
export const PASSWORDS = [
  'AGENTX_LOCAL_POSTGRES_ADMIN_PASSWORD',
  'AGENTX_LOCAL_DB_OWNER_PASSWORD',
  'AGENTX_LOCAL_DB_APP_PASSWORD',
  'AGENTX_LOCAL_DB_BACKUP_PASSWORD',
  'AGENTX_LOCAL_ZITADEL_DB_PASSWORD',
  'AGENTX_LOCAL_ZITADEL_ADMIN_PASSWORD',
] as const;

/** Zitadel encrypts its own secrets with this; it must be exactly 32 characters. */
export const MASTER_KEY = 'AGENTX_LOCAL_ZITADEL_MASTERKEY';

/**
 * The login container's key pair (ADR-003): Zitadel gets the public half and
 * the login container the private half, each as base64 of its PEM text, so
 * each fits on one line.
 */
export const LOGIN_CLIENT_KEYS = {
  public: 'AGENTX_LOCAL_LOGIN_CLIENT_PUBLIC_KEY',
  private: 'AGENTX_LOCAL_LOGIN_CLIENT_PRIVATE_KEY',
} as const;

/** Every variable the file holds, in the order it's written. */
export const VARIABLES: readonly string[] = [
  ...PASSWORDS,
  MASTER_KEY,
  LOGIN_CLIENT_KEYS.public,
  LOGIN_CLIENT_KEYS.private,
];

export type Random = (bytes: number) => Buffer;
export type KeyPair = () => { readonly publicPem: string; readonly privatePem: string };

/**
 * 128 random bits as hex, plus one character of each kind Zitadel's default
 * password rules ask for (upper case, lower case, digit, symbol), so the same
 * shape serves every login. Nothing in it means anything to a shell, YAML or
 * a compose .env file.
 */
export function newPassword(random: Random = randomBytes): string {
  return `${random(16).toString('hex')}aZ9!`;
}

/** 32 characters, as Zitadel requires. */
export function newMasterKey(random: Random = randomBytes): string {
  return random(16).toString('hex');
}

/** RSA, as Zitadel's system users take it: 3072 bits, the public half as SPKI and the private as PKCS#8. */
export const newKeyPair: KeyPair = () => {
  const pair = generateKeyPairSync('rsa', {
    modulusLength: 3072,
    publicKeyEncoding: { type: 'spki', format: 'pem' },
    privateKeyEncoding: { type: 'pkcs8', format: 'pem' },
  });
  return { publicPem: pair.publicKey, privatePem: pair.privateKey };
};

/** The file's text: one `NAME=value` line per variable, in a fixed order. */
export function renderEnv(values: Readonly<Record<string, string>>): string {
  const lines = Object.entries(values).map(([name, value]) => `${name}=${value}`);
  return `# Generated by deploy/compose/prepare.ts. Local logins: never commit, never share.\n${lines.join('\n')}\n`;
}

export function generate(random: Random = randomBytes, keyPair: KeyPair = newKeyPair): Record<string, string> {
  const keys = keyPair();
  return {
    ...Object.fromEntries(PASSWORDS.map((name) => [name, newPassword(random)])),
    [MASTER_KEY]: newMasterKey(random),
    [LOGIN_CLIENT_KEYS.public]: Buffer.from(keys.publicPem).toString('base64'),
    [LOGIN_CLIENT_KEYS.private]: Buffer.from(keys.privatePem).toString('base64'),
  };
}

/** The names an existing file already sets. */
const namesIn = (text: string): Set<string> =>
  new Set(
    text
      .split('\n')
      .filter((line) => !line.startsWith('#') && line.includes('='))
      .map((line) => line.slice(0, line.indexOf('=')).trim()),
  );

/**
 * Writes the file unless it exists: `wx` lets the file system decide, so two
 * runs at once can't both write it. An existing file keeps every value it
 * has; only the variables it lacks are added. Returns what happened, never a
 * value.
 */
export function prepare(
  file: string = ENV_FILE,
  random: Random = randomBytes,
  keyPair: KeyPair = newKeyPair,
): 'created' | 'kept' | 'added' {
  const values = generate(random, keyPair);
  try {
    writeFileSync(file, renderEnv(values), { mode: 0o600, flag: 'wx' });
    return 'created';
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== 'EEXIST') throw error;
  }
  const existing = readFileSync(file, 'utf8');
  const present = namesIn(existing);
  const missing = VARIABLES.filter((name) => !present.has(name));
  if (missing.length === 0) return 'kept';
  const separator = existing.endsWith('\n') || existing === '' ? '' : '\n';
  appendFileSync(file, `${separator}${missing.map((name) => `${name}=${values[name] ?? ''}`).join('\n')}\n`);
  return 'added';
}

if (import.meta.main) {
  const outcome = prepare();
  const messages = {
    created: `Wrote ${ENV_FILE} with new logins for the local stack.`,
    added: `Added the values the stack has come to need to ${ENV_FILE}, keeping every value it had.`,
    kept: `Kept ${ENV_FILE}: the stack's logins already exist. Delete it (and the stack's volumes) to start afresh.`,
  };
  console.log(messages[outcome]);
}
